import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/pages/login/_login.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.login}>
      <Head>
        <title>Flo&apos;s repo - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      On est au login
    </div>
  )
}

export default Home
