import type { InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import styles from 'styles/pages/login/_login.module.scss';
import request from 'utils/request';
import { IRandomData } from './slice/types';

export const getServerSideProps = async () => {
  const quotes = await request<IRandomData>('https://quotes.rest/qod');

  return {
    props: {
      data: quotes,
    },
  };
};

export default function Home({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className={styles.login}>
      <Head>
        <title>Flo&apos;s repo - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      On est au login:
      {data ? data.contents.quotes.map(quote => <p key={quote.id}>{quote.quote}</p>) : null}
    </div>
  );
}
