import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import styles from 'styles/pages/login/_login.module.scss';
import { useLoginSlice } from './slice';
import { selectLoginQuote } from './slice/selectors';

const Home: NextPage = () => {
  const { actions } = useLoginSlice();
  const dispatch = useDispatch();
  const { data } = useSelector(selectLoginQuote);

  useEffect(() => {
    dispatch(actions.getRandomData());
  }, []);

  
  return (
    <div className={styles.login}>
      <Head>
        <title>Flo&apos;s repo - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      On est au login:

      {data ? data.contents.quotes.map(quote => (
        <p key={quote.id}>{quote.quote}</p>
      )): null}
    </div>
  )
}

export default Home
